const USER_TYPES = {
  SET_USERNAME: "SET_USERNAME",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN",
  SET_NAME: "SET_NAME",
  SET_PICTURE: "SET_PICTURE",
  SET_STATUS: "SET_STATUS",
  SET_PHONENUMBER: "SET_PHONENUMBER",
  SET___ID: "SET___ID",
  SET_NEW_MESSAGES: "SET_NEW_MESSAGES",
  ADD_NOTIFICATIONS: "SET_NEW_NOTIFICATIONS",
  RESET_NOTIFICATIONS: "RESET_NOTIFICATIONS",
};

export { USER_TYPES };
